$parts = @(
"InVzZSBjbGllbnQiOwoKaW1wb3J0IHsgdXNlUm91dGVyIH0gZnJvbSAibmV4dC9uYXZpZ2F0aW9uIjsKaW1wb3J0IHsgdXNlQ2Fy",
"dCB9IGZyb20gIi4vQ2FydFByb3ZpZGVyIjsKCmV4cG9ydCBkZWZhdWx0IGZ1bmN0aW9uIEFkZFRvUmVzb3VyY2VDYXJ0QnV0dG9u",
"KHsgcmVzb3VyY2UgfSkgewogIGNvbnN0IHsgYWRkSXRlbSB9ID0gdXNlQ2FydCgpOwogIGNvbnN0IHJvdXRlciA9IHVzZVJvdXRl",
"cigpOwoKICBmdW5jdGlvbiBoYW5kbGVDbGljaygpIHsKICAgIGFkZEl0ZW0oewogICAgICBzbHVnOiByZXNvdXJjZS5zbHVnLAog",
"ICAgICB0aXRsZTogcmVzb3VyY2UudGl0bGUsCiAgICAgIHByaWNlOiByZXNvdXJjZS5wcmljZSwKICAgICAgZm9ybWF0OiAicmVz",
"b3VyY2UiLAogICAgfSk7CgogICAgaWYgKHR5cGVvZiB3aW5kb3cgIT09ICJ1bmRlZmluZWQiKSB7CiAgICAgIHdpbmRvdy5mYnEg",
"JiYgd2luZG93LmZicSgidHJhY2siLCAiQWRkVG9DYXJ0IiwgewogICAgICAgIGNvbnRlbnRfbmFtZTogcmVzb3VyY2UudGl0bGUs",
"CiAgICAgICAgY29udGVudF90eXBlOiAicHJvZHVjdCIsCiAgICAgICAgY3VycmVuY3k6ICJVU0QiLAogICAgICAgIHZhbHVlOiBy",
"ZXNvdXJjZS5wcmljZSwKICAgICAgfSk7CiAgICAgIHdpbmRvdy5ndGFnICYmIHdpbmRvdy5ndGFnKCJldmVudCIsICJhZGRfdG9f",
"Y2FydCIsIHsKICAgICAgICBjdXJyZW5jeTogIlVTRCIsCiAgICAgICAgdmFsdWU6IHJlc291cmNlLnByaWNlLAogICAgICAgIGl0",
"ZW1zOiBbeyBpdGVtX25hbWU6IHJlc291cmNlLnRpdGxlLCBwcmljZTogcmVzb3VyY2UucHJpY2UgfV0sCiAgICAgIH0pOwogICAg",
"fQoKICAgIHJvdXRlci5wdXNoKCIvY2hlY2tvdXQiKTsKICB9CgogIHJldHVybiAoCiAgICA8YnV0dG9uIGNsYXNzTmFtZT0iYnRu",
"IGJ0bi1kYXJrIGJ0bi1zbSBidG4tYmxvY2siIG9uQ2xpY2s9e2hhbmRsZUNsaWNrfT4KICAgICAgQnV5IE5vdyDigJQgJHtyZXNv",
"dXJjZS5wcmljZS50b0ZpeGVkKDIpfQogICAgPC9idXR0b24+CiAgKTsKfQo="
)
$b64 = $parts -join ""
[System.IO.File]::WriteAllBytes("components\AddToResourceCartButton.js", [Convert]::FromBase64String($b64))
Write-Host "Done writing components\AddToResourceCartButton.js -- base64 length:" $b64.Length "(expected 1360)"
