$parts = @(
"ZXhwb3J0IGRlZmF1bHQgewogIG5hbWU6ICJ3ZWJpbmFyUmVnaXN0cmF0aW9uIiwKICB0aXRsZTogIldlYmluYXIgUmVnaXN0cmF0",
"aW9uIiwKICB0eXBlOiAiZG9jdW1lbnQiLAogIGZpZWxkczogWwogICAgewogICAgICBuYW1lOiAiZXZlbnRUaXRsZSIsCiAgICAg",
"IHRpdGxlOiAiV2ViaW5hciIsCiAgICAgIHR5cGU6ICJzdHJpbmciLAogICAgfSwKICAgIHsKICAgICAgbmFtZTogImV2ZW50U2x1",
"ZyIsCiAgICAgIHRpdGxlOiAiV2ViaW5hciBTbHVnIiwKICAgICAgdHlwZTogInN0cmluZyIsCiAgICB9LAogICAgewogICAgICBu",
"YW1lOiAibmFtZSIsCiAgICAgIHRpdGxlOiAiQXR0ZW5kZWUgTmFtZSIsCiAgICAgIHR5cGU6ICJzdHJpbmciLAogICAgICBkZXNj",
"cmlwdGlvbjogIkNvbGxlY3RlZCBvbiBmcmVlIHJlZ2lzdHJhdGlvbi4gTm90IGN1cnJlbnRseSBjb2xsZWN0ZWQgb24gcGFpZCBy",
"ZWdpc3RyYXRpb24gKG9ubHkgZW1haWwgaXMgYXNrZWQgZm9yIGF0IGNoZWNrb3V0KS4iLAogICAgfSwKICAgIHsKICAgICAgbmFt",
"ZTogImVtYWlsIiwKICAgICAgdGl0bGU6ICJBdHRlbmRlZSBFbWFpbCIsCiAgICAgIHR5cGU6ICJzdHJpbmciLAogICAgfSwKICAg",
"IHsKICAgICAgbmFtZTogInBhaWQiLAogICAgICB0aXRsZTogIlBhaWQgUmVnaXN0cmF0aW9uPyIsCiAgICAgIHR5cGU6ICJib29s",
"ZWFuIiwKICAgICAgaW5pdGlhbFZhbHVlOiBmYWxzZSwKICAgIH0sCiAgICB7CiAgICAgIG5hbWU6ICJyZWZlcmVuY2UiLAogICAg",
"ICB0aXRsZTogIlBheW1lbnQgUmVmZXJlbmNlIChpZiBwYWlkKSIsCiAgICAgIHR5cGU6ICJzdHJpbmciLAogICAgfSwKICAgIHsK",
"ICAgICAgbmFtZTogInJlZ2lzdGVyZWRBdCIsCiAgICAgIHRpdGxlOiAiUmVnaXN0ZXJlZCBBdCIsCiAgICAgIHR5cGU6ICJkYXRl",
"dGltZSIsCiAgICB9LAogIF0sCiAgcHJldmlldzogewogICAgc2VsZWN0OiB7IHRpdGxlOiAibmFtZSIsIHN1YnRpdGxlOiAiZXZl",
"bnRUaXRsZSIgfSwKICB9LAp9Owo="
)
$b64 = $parts -join ""
[System.IO.File]::WriteAllBytes("sanity\schemas\webinarRegistration.js", [Convert]::FromBase64String($b64))
Write-Host "Done writing sanity\schemas\webinarRegistration.js -- base64 length:" $b64.Length "(expected 1328)"
