export default {
  name: "book",
  title: "Book",
  type: "document",
  fields: [
    { name: "title", title: "Title", type: "string", validation: (Rule) => Rule.required() },
    { name: "slug", title: "URL Slug", type: "slug", options: { source: "title", maxLength: 96 }, validation: (Rule) => Rule.required() },
    { name: "subtitle", title: "Subtitle", type: "string" },
    { name: "coverImage", title: "Cover Image", type: "image", options: { hotspot: true } },
    { name: "blurb", title: "Short Blurb", type: "text", rows: 3 },
    { name: "longDescription", title: "Full Description", type: "array", of: [{ type: "block" }] },
    { name: "sampleChapter", title: "Sample Chapter Excerpt", type: "text", rows: 8 },
    { name: "price", title: "eBook Price (USD)", type: "number", validation: (Rule) => Rule.required().positive() },
    { name: "paperbackPrice", title: "Paperback Price (USD)", type: "number", description: "Leave blank if this book is not available as a paperback." },
    { name: "weightKg", title: "Paperback Weight (kg)", type: "number", description: "Used to calculate shipping cost. Only needed if this book has a Paperback Price set. e.g. 0.4 for a typical paperback.", validation: (Rule) => Rule.positive() },
    { name: "oldPrice", title: "Original Price (for discounts, optional)", type: "number" },
    { name: "format", title: "Available Formats", type: "string", description: "e.g. eBook · Paperback · Audiobook" },
    { name: "category", title: "Category", type: "string", options: { list: ["Fiction", "Essays", "Memoir", "Nonfiction"] } },
    { name: "featured", title: "Featured on Homepage?", type: "boolean", initialValue: false },
    { name: "stripePriceId", title: "Stripe Price ID", type: "string", description: "Leave blank until Stripe is set up." },
    { name: "selarEbookUrl", title: "Selar eBook Buy Link", type: "url", description: "Paste your Selar product link for the eBook. Example: https://selar.co/xxxxxxxx" },
    { name: "selarAudioUrl", title: "Selar Audiobook Buy Link", type: "url", description: "Paste your Selar product link for the Audiobook. Example: https://selar.co/xxxxxxxx" },
    {
      name: "digitalFile",
      title: "Digital File (for site checkout delivery)",
      type: "file",
      description: "Upload the actual PDF/ebook file here. This is what gets emailed to buyers who purchase through this site's own cart checkout (not needed for Selar — Selar handles its own delivery).",
    },
  ],
  preview: {
    select: { title: "title", subtitle: "subtitle", media: "coverImage" },
  },
};