export default {
  name: "event",
  title: "Event",
  type: "document",
  fields: [
    {
      name: "title",
      title: "Event Title",
      type: "string",
      description: "Example: Lagos Literary Festival 2026",
      validation: (Rule) => Rule.required(),
    },
    {
      name: "slug",
      title: "URL Slug",
      type: "slug",
      options: { source: "title", maxLength: 96 },
      description: "Needed for webinars so the site can look up the event for registration/payment. Optional for other event types.",
      validation: (Rule) => Rule.required(),
    },
    {
      name: "date",
      title: "Event Date",
      type: "datetime",
      description: "When is the event?",
    },
    {
      name: "location",
      title: "Location",
      type: "string",
      description: "Example: Terra Kulture, Lagos or Online (Zoom)",
    },
    {
      name: "description",
      title: "Event Description",
      type: "text",
      rows: 4,
      description: "What is the event about?",
    },
    {
      name: "ticketUrl",
      title: "Ticket or Registration Link (external)",
      type: "url",
      description: "For non-webinar events only — an external ticketing link (e.g. Eventbrite). Leave empty for webinars; use the fields below instead.",
    },
    {
      name: "type",
      title: "Event Type",
      type: "string",
      options: {
        list: [
          { title: "Book Launch", value: "launch" },
          { title: "Speaking Engagement", value: "speaking" },
          { title: "Literary Festival", value: "festival" },
          { title: "Workshop", value: "workshop" },
          { title: "Panel Discussion", value: "panel" },
          { title: "Online Event", value: "online" },
          { title: "Webinar", value: "webinar" },
        ],
      },
    },
    {
      name: "price",
      title: "Webinar Price (USD) — leave empty if free",
      type: "number",
      description: "Only used when Event Type is Webinar. Leave empty for a free webinar.",
    },
    {
      name: "platform",
      title: "Webinar Platform",
      type: "string",
      description: "Only used when Event Type is Webinar. Example: Zoom, Google Meet, YouTube Live — shown in the confirmation email, not on the public page.",
    },
    {
      name: "joinLink",
      title: "Webinar Join Link (private)",
      type: "url",
      description: "Only used when Event Type is Webinar. The actual Zoom/Meet link. This is NEVER shown on the public site — it is only emailed to people after they register (free) or pay (paid).",
    },
    {
      name: "coverImage",
      title: "Event Image or Flyer",
      type: "image",
      options: { hotspot: true },
    },
    {
      name: "featured",
      title: "Show as upcoming event?",
      type: "boolean",
      initialValue: true,
    },
  ],
  preview: {
    select: { title: "title", subtitle: "date" },
  },
};
