import post from "./post";
import book from "./book";
import resource from "./resource";
import sibtechProduct from "./sibtechProduct";
import event from "./event";
import homePage from "./homePage";
import aboutPage from "./aboutPage";
import contactPage from "./contactPage";
import myStoryPage from "./myStoryPage";
import architecturePage from "./architecturePage";
import project from "./project";
import contactSubmission from "./contactSubmission";
import subscriber from "./subscriber";
import testimonial from "./testimonial";
import delivery from "./delivery";
import physicalOrder from "./physicalOrder";
import shippingSettings from "./shippingSettings";
import webinarRegistration from "./webinarRegistration";
import abandonedCart from "./abandonedCart";

export const schemaTypes = [post, book, resource, sibtechProduct, event, homePage, aboutPage, contactPage, myStoryPage, architecturePage, project, contactSubmission, subscriber, testimonial, delivery, physicalOrder, shippingSettings, webinarRegistration, abandonedCart];