export default {
  name: "sitePage",
  title: "Site Pages",
  type: "document",
  groups: [
    { name: "hero", title: "🏠 Hero Section (Top of page)" },
    { name: "quote", title: "💬 Your Quote" },
    { name: "whyiwrite", title: "✍️ Why I Write Section" },
    { name: "about", title: "👤 About Page" },
    { name: "contact", title: "📬 Contact Page" },
  ],
  fields: [
    {
      name: "pageId",
      title: "Which page is this?",
      type: "string",
      description: "⚠️ Do not change this — it tells the site which page to update.",
      options: {
        list: [
          { title: "Home Page", value: "home" },
          { title: "About Page", value: "about" },
          { title: "Contact Page", value: "contact" },
        ],
      },
    },
    {
      name: "homeAuthorPhoto",
      title: "Your Photo (shown on homepage)",
      type: "image",
      description: "Upload your author photo here. Click Upload and choose your photo.",
      options: { hotspot: true },
      group: "hero",
    },
    {
      name: "homeEyebrow",
      title: "Small text above the heading",
      type: "string",
      description: "Example: Nigerian Author | Exploring Belief, Culture, Identity, and Human Freedom",
      group: "hero",
    },
    {
      name: "homeHeading",
      title: "Main heading (big title on homepage)",
      type: "string",
      description: "Example: The Stories We Inherit. The Truths We Choose.",
      group: "hero",
    },
    {
      name: "homeSubheading",
      title: "First paragraph under the heading",
      type: "text",
      rows: 3,
      description: "This appears directly under your main heading.",
      group: "hero",
    },
    {
      name: "homeIntro",
      title: "Introduction paragraph (who you are)",
      type: "text",
      rows: 4,
      description: "This is where you introduce yourself — who you are and what you write.",
      group: "hero",
    },
    {
      name: "homeQuote",
      title: "Your featured quote",
      type: "text",
      rows: 3,
      description: "Appears in the dark green section. Example: The most powerful prisons are rarely built with walls...",
      group: "quote",
    },
    {
      name: "homeWhyIWrite",
      title: "Why I Write — Paragraph 1",
      type: "text",
      rows: 4,
      description: "First paragraph of your Why I Write section.",
      group: "whyiwrite",
    },
    {
      name: "homeWhyIWrite2",
      title: "Why I Write — Paragraph 2",
      type: "text",
      rows: 4,
      description: "Second paragraph of your Why I Write section.",
      group: "whyiwrite",
    },
    {
      name: "homeWhyIWrite3",
      title: "Why I Write — Paragraph 3 (closing question)",
      type: "text",
      rows: 3,
      description: "The closing question or thought.",
      group: "whyiwrite",
    },
    {
      name: "aboutPhoto",
      title: "Your Photo (shown on About page)",
      type: "image",
      description: "Upload your photo for the About page.",
      options: { hotspot: true },
      group: "about",
    },
    {
      name: "aboutHeading",
      title: "About Page — Main Heading",
      type: "string",
      description: "Example: About the Author",
      group: "about",
    },
    {
      name: "aboutSubheading",
      title: "About Page — Subheading",
      type: "string",
      description: "Example: Writer. Independent publisher. Keeper of family stories.",
      group: "about",
    },
    {
      name: "aboutBio",
      title: "Your Biography — Paragraph 1",
      type: "text",
      rows: 6,
      description: "Write about yourself, your background, and your work.",
      group: "about",
    },
    {
      name: "aboutBio2",
      title: "Your Biography — Paragraph 2",
      type: "text",
      rows: 6,
      description: "Continue your biography here.",
      group: "about",
    },
    {
      name: "aboutPullQuote",
      title: "Your favourite personal quote",
      type: "text",
      rows: 3,
      description: "A quote about your writing philosophy.",
      group: "about",
    },
    {
      name: "aboutInfluences",
      title: "Writers who influenced you",
      type: "array",
      of: [{ type: "string" }],
      description: "Click Add item and type a name. Example: Chinua Achebe",
      group: "about",
    },
    {
      name: "aboutAwards",
      title: "Awards and Publications",
      type: "array",
      of: [{
        type: "object",
        title: "Award or Publication",
        fields: [
          { name: "year", title: "Year (e.g. 2025)", type: "string" },
          { name: "title", title: "Award or publication title", type: "string" },
        ],
      }],
      description: "Click Add item for each award or publication.",
      group: "about",
    },
    {
      name: "contactEmail",
      title: "Your Email Address",
      type: "string",
      description: "Example: hello@solomonbibe.com",
      group: "contact",
    },
    {
      name: "contactLocation",
      title: "Your Location",
      type: "string",
      description: "Example: Lagos, Nigeria",
      group: "contact",
    },
    {
      name: "contactResponseTime",
      title: "How quickly you respond",
      type: "string",
      description: "Example: Within 2-3 business days",
      group: "contact",
    },
    {
      name: "contactInstagram",
      title: "Instagram Profile Link",
      type: "url",
      description: "Example: https://instagram.com/solomonbibe",
      group: "contact",
    },
    {
      name: "contactTwitter",
      title: "X / Twitter Profile Link",
      type: "url",
      description: "Example: https://x.com/solomonbibe",
      group: "contact",
    },
    {
      name: "contactFacebook",
      title: "Facebook Profile Link",
      type: "url",
      description: "Paste your full Facebook URL.",
      group: "contact",
    },
  ],
  preview: {
    select: { title: "pageId" },
    prepare({ title }) {
      const labels = {
        home: "🏠 Home Page",
        about: "👤 About Page",
        contact: "📬 Contact Page"
      };
      return { title: labels[title] || "Site Page" };
    },
  },
};